
server.port: 8082

spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/running_stats?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: run-admin
    password: admin
